### PR TITLE
Prepare Routes and testing via sample.http

### LINKED ISSUE #2: Prepare routes
#### Prepare routes for API Request

Add routes

#### Example

[Pullrequest for Photoplay](https://github.com/lmachens/photoplay/pull/49/commits/0f18a3b52c3adcec2444cbcd09931213ddfed235)

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Add src/server/routes.ts
- [x] Insert routes ( e.g '/movies/popular')

### PR DESCRIPTION
**Pull request by Niklas-Schaefers**
fixes #2

### CODE REVIEW

**Review by Dev-dfm — APPROVED** [review]
lgtm 👍

**Review by lmachens — COMMENTED** [review]
You are ready to start :).
I would load environment variable PORT in `sample.http` too, if you run your server on a different port.
And a deployment would be great to test your endpoint.

**Review by daebert — COMMENTED** [review]
lgtm!

**Review by roabram — COMMENTED** [review]
lgtm :)

**Pull request merged**
